# docker-compose.yml
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  bocoai:
    build: ./bocoai
    ports:
      - 8888:8000
    depends_on:
      - db
  bocoai-storefront:
    build: ./bocoai-storefront
    ports:
      - 3333:3000
    depends_on:
      - bocoai